apiVersion: batch/v1
kind: Job
metadata:
  name: tflkubeml
spec:
  template:
    spec:
      initContainers:
      - name: delete-models-directory
        image: busybox:1.35 # Using a lightweight image to run the deletion command
        command: ['sh', '-c', 'rm -rf /opt/spark-app/models/*']  # Command to delete the contents of the directory
        volumeMounts:
        - name: models-volume
          mountPath: /opt/spark-app/models  # Mount the volume at the location
      containers:
      - name: pysparkml
        image: uttamraj9/tflkubeml:latest
        volumeMounts:
        - mountPath: /opt/spark-app/models  # Container path where the models will be mounted
          name: models-volume              # Name of the volume to mount
      restartPolicy: Never
      volumes:
      - name: models-volume
        hostPath:
          path: /var/lib/jenkins/workspace/TfLKubeMl/kubemlPr/  # Path on the host machine
          type: Directory               # Specify the type as Directory to ensure it's a directory mount
  backoffLimit: 4
