apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-pv
spec:
  capacity:
    storage: 1Gi  # Adjust as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/jenkins/workspace/TfLKubeMl/kubemlPr/models  # Path on the worker node
    type: Directory
