apiVersion: batch/v1
kind: CronJob
metadata:
  name: tflkubeml
spec:
  schedule: "*/5 * * * *"  # This runs the job every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pysparkmlpr
            image: uttamraj9/tflkubemlpr:latest
          restartPolicy: Never
  backoffLimit: 4
